export default function Frame() {
  return (
    <div className="relative size-full">
      <div className="absolute font-['Roboto:Regular',sans-serif] font-normal h-[673px] leading-[22px] left-0 text-[14px] text-[rgba(0,0,0,0.8)] top-0 w-[344px]" style={{ fontVariationSettings: "'wdth' 100" }}>
        <p className="css-4hzbpn mb-0">{`{ `}</p>
        <p className="css-4hzbpn mb-0">{`  "pressRelease": { `}</p>
        <p className="css-4hzbpn mb-0">{`    "id": "PR-2025-0924", `}</p>
        <p className="css-4hzbpn mb-0">{`    "title": "Launch of New HealthCare Portal", `}</p>
        <p className="css-4hzbpn mb-0">{`    "date": "2025-09-24T10:30:00Z", `}</p>
        <p className="css-4hzbpn mb-0">{`    "author": { `}</p>
        <p className="css-4hzbpn mb-0">{`      "name": "John Doe", `}</p>
        <p className="css-4hzbpn mb-0">{`      "email": "john.doe@example.com", `}</p>
        <p className="css-4hzbpn mb-0">{`      "organization": "HealthTech Innovations" `}</p>
        <p className="css-4hzbpn mb-0">{`    }, `}</p>
        <p className="css-4hzbpn mb-0">{`    "summary": "We are excited to announce the launch of our new healthcare portal designed to streamline patient-provider communication.", `}</p>
        <p className="css-4hzbpn mb-0">{`    "contentSections": [ `}</p>
        <p className="css-4hzbpn mb-0">{`      { `}</p>
        <p className="css-4hzbpn mb-0">{`        "heading": "Overview", `}</p>
        <p className="css-4hzbpn mb-0">{`        "body": "Our new platform integrates eligibility verification, authorization requests, and billing in one easy-to-use dashboard." `}</p>
        <p className="css-4hzbpn mb-0">{`      }, `}</p>
        <p className="css-4hzbpn mb-0">{`      { `}</p>
        <p className="css-4hzbpn mb-0">{`        "heading": "Key Features", `}</p>
        <p className="css-4hzbpn mb-0">{`        "body": "Single sign-on, real-time claim status, secure document uploads.", `}</p>
        <p className="css-4hzbpn mb-0">{`        "features": [ `}</p>
        <p className="css-4hzbpn mb-0">{`          { `}</p>
        <p className="css-4hzbpn mb-0">{`            "name": "Eligibility Verification", `}</p>
        <p className="css-4hzbpn mb-0">{`            "description": "Instant checks with payors" `}</p>
        <p className="css-4hzbpn mb-0">{`          }, `}</p>
        <p className="css-4hzbpn mb-0">{`          { `}</p>
        <p className="css-4hzbpn mb-0">{`            "name": "Authorization Tracking", `}</p>
        <p className="css-4hzbpn mb-0">{`            "description": "Submit and monitor authorization requests" `}</p>
        <p className="css-4hzbpn mb-0">{`          }, `}</p>
        <p className="css-4hzbpn mb-0">{`          { `}</p>
        <p className="css-4hzbpn mb-0">{`            "name": "Cash Posting", `}</p>
        <p className="css-4hzbpn mb-0">{`            "description": "Simplified payment posting workflows" `}</p>
        <p className="css-4hzbpn mb-0">{`          } `}</p>
        <p className="css-4hzbpn mb-0">{`        ] `}</p>
        <p className="css-4hzbpn mb-0">{`      }, `}</p>
        <p className="css-4hzbpn mb-0">{`      { `}</p>
        <p className="css-4hzbpn mb-0">{`        "heading": "Testimonials", `}</p>
        <p className="css-4hzbpn mb-0">{`        "testimonials": [ `}</p>
        <p className="css-4hzbpn mb-0">{`          { `}</p>
        <p className="css-4hzbpn mb-0">{`            "user": "Dr. Smith", `}</p>
        <p className="css-4hzbpn mb-0">{`            "comment": "This system has reduced my admin time by 40%!" `}</p>
        <p className="css-4hzbpn mb-0">{`          }, `}</p>
        <p className="css-4hzbpn mb-0">{`          { `}</p>
        <p className="css-4hzbpn mb-0">{`            "user": "Jane, RN", `}</p>
        <p className="css-4hzbpn mb-0">{`            "comment": "Finally a portal that’s intuitive and reliable." `}</p>
        <p className="css-4hzbpn mb-0">{`          } `}</p>
        <p className="css-4hzbpn mb-0">{`        ] `}</p>
        <p className="css-4hzbpn mb-0">{`      } `}</p>
        <p className="css-4hzbpn mb-0">{`    ], `}</p>
        <p className="css-4hzbpn mb-0">{`    "ctaOptions": [ `}</p>
        <p className="css-4hzbpn mb-0">{`      { `}</p>
        <p className="css-4hzbpn mb-0">{`        "id": "cta-1", `}</p>
        <p className="css-4hzbpn mb-0">{`        "text": "Sign Up for Free Trial", `}</p>
        <p className="css-4hzbpn mb-0">{`        "url": "https://portal.example.com/signup" `}</p>
        <p className="css-4hzbpn mb-0">{`      }, `}</p>
        <p className="css-4hzbpn mb-0">{`      { `}</p>
        <p className="css-4hzbpn mb-0">{`        "id": "cta-2", `}</p>
        <p className="css-4hzbpn mb-0">{`        "text": "Request a Demo", `}</p>
        <p className="css-4hzbpn mb-0">{`        "url": "https://portal.example.com/demo" `}</p>
        <p className="css-4hzbpn mb-0">{`      }, `}</p>
        <p className="css-4hzbpn mb-0">{`      { `}</p>
        <p className="css-4hzbpn mb-0">{`        "id": "cta-3", `}</p>
        <p className="css-4hzbpn mb-0">{`        "text": "Download Product Brochure", `}</p>
        <p className="css-4hzbpn mb-0">{`        "url": "https://portal.example.com/brochure.pdf" `}</p>
        <p className="css-4hzbpn mb-0">{`      } `}</p>
        <p className="css-4hzbpn mb-0">{`    ], `}</p>
        <p className="css-4hzbpn mb-0">{`    "tags": ["Healthcare", "Portal", "Authorization", "Eligibility", "Cash Posting"], `}</p>
        <p className="css-4hzbpn mb-0">{`    "meta": { `}</p>
        <p className="css-4hzbpn mb-0">{`      "language": "en", `}</p>
        <p className="css-4hzbpn mb-0">{`      "region": "US", `}</p>
        <p className="css-4hzbpn mb-0">{`      "keywords": ["healthtech", "authorization portal", "patient management"], `}</p>
        <p className="css-4hzbpn mb-0">{`      "createdBy": "PR Team", `}</p>
        <p className="css-4hzbpn mb-0">{`      "lastUpdated": "2025-09-24T11:00:00Z", `}</p>
        <p className="css-4hzbpn mb-0">{`      "contactInfo": { `}</p>
        <p className="css-4hzbpn mb-0">{`        "phone": "+1-800-555-1234", `}</p>
        <p className="css-4hzbpn mb-0">{`        "supportEmail": "support@example.com", `}</p>
        <p className="css-4hzbpn mb-0">{`        "social": { `}</p>
        <p className="css-4hzbpn mb-0">{`          "twitter": "https://twitter.com/healthtech", `}</p>
        <p className="css-4hzbpn mb-0">{`          "linkedin": "https://linkedin.com/company/healthtech" `}</p>
        <p className="css-4hzbpn mb-0">{`        } `}</p>
        <p className="css-4hzbpn mb-0">{`      } `}</p>
        <p className="css-4hzbpn mb-0">{`    }, `}</p>
        <p className="css-4hzbpn mb-0">{`    "relatedPressReleases": [ `}</p>
        <p className="css-4hzbpn mb-0">{`      { `}</p>
        <p className="css-4hzbpn mb-0">{`        "id": "PR-2025-0820", `}</p>
        <p className="css-4hzbpn mb-0">{`        "title": "Partnership with MediPay", `}</p>
        <p className="css-4hzbpn mb-0">{`        "url": "https://example.com/press/PR-2025-0820" `}</p>
        <p className="css-4hzbpn mb-0">{`      }, `}</p>
        <p className="css-4hzbpn mb-0">{`      { `}</p>
        <p className="css-4hzbpn mb-0">{`        "id": "PR-2025-0710", `}</p>
        <p className="css-4hzbpn mb-0">{`        "title": "Launch of Authorization Agent Beta", `}</p>
        <p className="css-4hzbpn mb-0">{`        "url": "https://example.com/press/PR-2025-0710" `}</p>
        <p className="css-4hzbpn mb-0">{`      } `}</p>
        <p className="css-4hzbpn mb-0">{`    ] `}</p>
        <p className="css-4hzbpn mb-0">{`  } `}</p>
        <p className="css-4hzbpn mb-0">{`} `}</p>
        <p className="css-4hzbpn">&nbsp;</p>
      </div>
    </div>
  );
}